param(
    [switch]$SkipDocker
)

$ErrorActionPreference = "Stop"
$root = Resolve-Path (Join-Path $PSScriptRoot "..")

function Assert-File {
    param([string]$Path)
    $full = Join-Path $root $Path
    if (-not (Test-Path -LiteralPath $full -PathType Leaf)) {
        throw "Missing required file: $Path"
    }
}

function Assert-Directory {
    param([string]$Path)
    $full = Join-Path $root $Path
    if (-not (Test-Path -LiteralPath $full -PathType Container)) {
        throw "Missing required directory: $Path"
    }
}

function Assert-Contains {
    param([string]$Path, [string]$Pattern, [string]$Description)
    $full = Join-Path $root $Path
    $content = Get-Content -Raw -LiteralPath $full
    if ($content -notmatch $Pattern) {
        throw "$Path does not contain required content: $Description"
    }
}

function Assert-NotContains {
    param([string]$Path, [string]$Pattern, [string]$Description)
    $full = Join-Path $root $Path
    $content = Get-Content -Raw -LiteralPath $full
    if ($content -match $Pattern) {
        throw "$Path contains forbidden content: $Description"
    }
}

Assert-File "README.md"
Assert-File "README.zh-CN.md"
Assert-File "docker-compose.yml"
Assert-File "docker-compose.dev.yml"
Assert-File "docker-compose.prod.yml"
Assert-File "docker-compose.edge.yml"
Assert-File "docker-compose.cpa.yml"
Assert-File "docker-compose.cpa.ui.yml"
Assert-File ".env.example"
Assert-File ".env.production.example"
Assert-File ".gitmodules"
Assert-File "Caddyfile"
Assert-File "Caddyfile.status.example"
Assert-File "Caddyfile.edge.example"
Assert-File ".gitignore"
Assert-File "AGENTS.md"
Assert-Directory "docs"
Assert-Directory "ops"
Assert-Directory "vendor/new-api"
Assert-Directory "vendor/cli-proxy-api"
Assert-Directory ".specify"
Assert-Directory ".agents/skills"

Assert-File "docs/operations-runbook.md"
Assert-File "docs/new-api-code-map.md"
Assert-File "docs/new-api-full-research.md"
Assert-File "docs/local-development-state.md"
Assert-File "docs/backup-strategy.md"
Assert-File "docs/server-buying-guide.md"
Assert-File "docs/development-workflow.md"
Assert-File "docs/spec-kit-integration-runbook.md"
Assert-File "docs/wrapper-infra-runbook.md"
Assert-File "docs/kuma-status-runbook.md"
Assert-File "docs/browser-e2e-runbook.md"
Assert-File "docs/production-deployment-runbook.md"
Assert-File "docs/release-deployment-runbook.md"
Assert-File "docs/edge-proxy-runbook.md"
Assert-File "docs/migration-runbook.md"
Assert-File "docs/disaster-recovery-runbook.md"
Assert-File "docs/git-branching-runbook.md"
Assert-File "docs/cpa-runbook.md"
Assert-File "docs/i18n-map.md"
Assert-Directory "docs/zh-CN"
Assert-File "docs/zh-CN/production-deployment-runbook.md"
Assert-File "docs/zh-CN/release-deployment-runbook.md"
Assert-File "docs/zh-CN/edge-proxy-runbook.md"
Assert-File "docs/zh-CN/migration-runbook.md"
Assert-File "docs/zh-CN/disaster-recovery-runbook.md"
Assert-File "docs/zh-CN/git-branching-runbook.md"
Assert-File "docs/zh-CN/cpa-runbook.md"
Assert-File "docs/zh-CN/backup-strategy.md"
Assert-File "docs/zh-CN/operations-runbook.md"
Assert-File "docs/zh-CN/server-buying-guide.md"
Assert-Directory "docs/ai-dev/2026-05-08-spec-kit-codex-init"
Assert-Directory "docs/ai-dev/2026-05-08-dual-health-monitoring"
Assert-Directory "docs/ai-dev/2026-05-10-prod-deploy-migration-kit"
Assert-Directory "docs/ai-dev/2026-05-10-docs-i18n-zh-cn"
Assert-Directory "docs/ai-dev/2026-05-10-git-branching-policy"
Assert-Directory "docs/ai-dev/2026-05-10-prod-deploy-lessons-hardening"
Assert-Directory "docs/ai-dev/2026-05-10-release-worktree-deploy"
Assert-Directory "docs/templates/ai-dev"
Assert-File "docs/templates/ai-dev/research.md"
Assert-File "docs/templates/ai-dev/spec.md"
Assert-File "docs/templates/ai-dev/plan.md"
Assert-File "docs/templates/ai-dev/tasks.md"
Assert-File "docs/templates/ai-dev/handoff.md"
Assert-File "ops/preflight.sh"
Assert-File "ops/backup-postgres.sh"
Assert-File "ops/verify-postgres-backup.sh"
Assert-File "ops/restore-postgres.sh"
Assert-File "ops/e2e-api-billing.sh"
Assert-File "ops/build-local-new-api.sh"
Assert-File "ops/start-local-new-api.sh"
Assert-File "ops/export-config-snapshot.sh"
Assert-File "ops/drill-restore-postgres.sh"
Assert-File "ops/drill-restore-stack.sh"
Assert-File "ops/production-gate.sh"
Assert-File "ops/ai-dev-check.sh"
Assert-File "ops/validate-ops-profile.sh"
Assert-File "ops/channel-health-advisor.sh"
Assert-File "ops/live-e2e-billing-from-db-token.sh"
Assert-File "ops/check-local-ports.sh"
Assert-File "ops/bootstrap-server.sh"
Assert-File "ops/deploy-prod.sh"
Assert-File "ops/deploy-release.sh"
Assert-File "ops/verify-remote-prod.sh"
Assert-File "ops/offsite-backup.sh"
Assert-File "ops/migration-preflight.sh"
Assert-File "ops/migrate-prod.sh"
Assert-File "ops/check-production-runtime.sh"
Assert-File "ops/sync-cpa-upstream-assets.sh"
Assert-File "tests/e2e-api-billing.test.sh"
Assert-File "tests/wrapper-infra.test.sh"
Assert-File "tests/ai-dev-check.test.sh"
Assert-File "tests/ops-profile.test.sh"
Assert-File "tests/spec-kit-init.test.sh"
Assert-File "tests/channel-health-advisor.test.sh"
Assert-File "tests/live-e2e-token-wrapper.test.sh"
Assert-File "tests/check-local-ports.test.sh"
Assert-File "tests/browser-e2e-scaffold.test.sh"
Assert-File "tests/prod-deploy-migration.test.sh"
Assert-File "tests/prod-deploy-hardening.test.sh"
Assert-File "tests/cpa-compose.test.sh"
Assert-File "tests/docs-i18n.test.sh"
Assert-File "tests/git-branching-policy.test.sh"
Assert-File "tests/release-deploy.test.sh"
Assert-File "config/ops-profiles/glm-standard.example.json"
Assert-File "config/ops-profiles/glm-standard-health.example.json"
Assert-File "package.json"
Assert-File "playwright.config.ts"
Assert-File "e2e/new-api-smoke.spec.ts"
Assert-File "e2e/kuma-status.spec.ts"
Assert-File "vendor/new-api/README.md"
Assert-File "vendor/cli-proxy-api/docker-compose.upstream.yml"
Assert-File "vendor/cli-proxy-api/config.example.yaml"
Assert-File ".specify/integration.json"
Assert-File ".specify/init-options.json"
Assert-File ".specify/scripts/bash/create-new-feature.sh"
Assert-File ".specify/scripts/bash/setup-plan.sh"
Assert-File ".specify/scripts/bash/setup-tasks.sh"
Assert-File ".specify/templates/spec-template.md"
Assert-File ".specify/templates/plan-template.md"
Assert-File ".specify/templates/tasks-template.md"
Assert-File ".specify/memory/constitution.md"
Assert-File ".agents/skills/speckit-specify/SKILL.md"
Assert-File ".agents/skills/speckit-plan/SKILL.md"
Assert-File ".agents/skills/speckit-tasks/SKILL.md"
Assert-File ".agents/skills/speckit-implement/SKILL.md"

Assert-Contains "docker-compose.yml" "calciumion/new-api" "New API image"
Assert-Contains "docker-compose.dev.yml" "NEW_API_DEV_PORT" "development port override"
Assert-Contains "docker-compose.dev.yml" "3100" "development host port default"
Assert-Contains "docker-compose.prod.yml" "!reset \[\]" "production override removes non-Caddy host ports"
Assert-Contains "docker-compose.edge.yml" "relay-edge-caddy" "edge Caddy service"
Assert-Contains "docker-compose.cpa.yml" "relay-cpa" "CPA internal service"
Assert-Contains "docker-compose.cpa.ui.yml" "127.0.0.1" "CPA UI localhost bind"
Assert-Contains "Caddyfile.edge.example" "ORIGIN_UPSTREAM" "edge origin upstream"
Assert-Contains "docker-compose.local-build.yml" "vendor/new-api" "local New API build context"
Assert-Contains ".gitmodules" "QuantumNous/new-api" "New API upstream submodule"
Assert-Contains "docker-compose.yml" "postgres" "PostgreSQL service"
Assert-Contains "docker-compose.yml" "redis" "Redis service"
Assert-Contains "docker-compose.yml" "caddy" "HTTPS reverse proxy"
Assert-Contains "docker-compose.yml" "uptime-kuma" "monitoring service"
Assert-Contains "Caddyfile.status.example" "STATUS_DOMAIN" "optional status domain"
Assert-Contains "Caddyfile.status.example" "uptime-kuma:3001" "Uptime Kuma reverse proxy target"
Assert-Contains ".env.example" "CHANGE_ME" "explicit placeholder secrets"
Assert-Contains ".env.example" "STATUS_DOMAIN=" "optional status domain variable"
Assert-Contains ".env.example" "KUMA_PORT=3011" "non-conflicting local Kuma port"
Assert-Contains ".env.production.example" "DEPLOY_ENV=production" "production env template"
Assert-Contains ".env.production.example" "DEPLOY_ROOT=/opt/lihan_ai_deploy" "release deploy root"
Assert-Contains ".env.production.example" "DEPLOY_COMPOSE_PROJECT=lihan_ai" "fixed release compose project"
Assert-Contains ".env.production.example" "DEPLOY_INCLUDE_CPA=0" "optional CPA release deploy toggle"
Assert-Contains ".env.production.example" "RELEASE_KEEP=5" "release cleanup retention"
Assert-Contains ".env.production.example" "RESTIC_REPOSITORY=" "off-server backup repository"
Assert-Contains ".env.production.example" "EDGE_DOMAIN=" "edge domain variable"
Assert-Contains "README.md" "README.zh-CN.md" "Chinese README link"
Assert-Contains "README.zh-CN.md" "DEPLOY_HOST=" "Chinese README deployment command"
Assert-Contains "docs/i18n-map.md" "docs/zh-CN/production-deployment-runbook.md" "i18n deployment mapping"
Assert-Contains "docs/i18n-map.md" "docs/zh-CN/release-deployment-runbook.md" "i18n release deployment mapping"
Assert-Contains "docs/git-branching-runbook.md" "main = production" "main production branch policy"
Assert-Contains "docs/zh-CN/git-branching-runbook.md" "main = production" "Chinese main production branch policy"
Assert-Contains "docs/cpa-runbook.md" "ssh -L 8317" "CPA SSH tunnel guidance"
Assert-Contains "docs/zh-CN/cpa-runbook.md" "ssh -L 8317" "Chinese CPA SSH tunnel guidance"
Assert-Contains "docs/new-api-code-map.md" "New API" "upstream feature map"
Assert-Contains "docs/new-api-full-research.md" "BillingSession" "billing research"
Assert-Contains "docs/local-development-state.md" "docker compose down -v" "state deletion warning"
Assert-Contains "docs/backup-strategy.md" "off-server" "off-server backup guidance"
Assert-Contains "docs/phase1-new-api-validation-runbook.md" "e2e-api-billing" "API billing e2e runbook"
Assert-Contains "docs/development-workflow.md" "Research Gate" "research workflow"
Assert-Contains "docs/development-workflow.md" "Research -> Spec -> Plan -> Tasks -> Implement -> Verify -> Commit" "spec-driven workflow"
Assert-Contains "docs/development-workflow.md" "speckit-specify" "Spec Kit Codex workflow"
Assert-Contains "docs/spec-kit-integration-runbook.md" "spec-kit.git@v0.8.7" "pinned Spec Kit install"
Assert-Contains "docs/spec-kit-integration-runbook.md" "specify init --here --offline --integration codex" "repository Spec Kit init"
Assert-Contains "docs/kuma-status-runbook.md" "API Gateway" "public status component"
Assert-Contains "docs/kuma-status-runbook.md" "GLM Standard" "public status model pool"
Assert-Contains "docs/browser-e2e-runbook.md" "KUMA_PORT=`"3011`"" "browser e2e Kuma port"
Assert-Contains "docs/production-deployment-runbook.md" "deploy-prod.sh" "production deployment command"
Assert-Contains "docs/release-deployment-runbook.md" "deploy-release.sh" "release deployment command"
Assert-Contains "docs/release-deployment-runbook.md" "/opt/lihan_ai_deploy" "release deployment root"
Assert-Contains "docs/zh-CN/release-deployment-runbook.md" "/opt/lihan_ai_deploy" "Chinese release deployment root"
Assert-Contains "docs/edge-proxy-runbook.md" "ORIGIN_UPSTREAM" "edge upstream variable"
Assert-Contains "docs/migration-runbook.md" "CONFIRM_FINAL_CUTOVER=yes" "migration confirmation"
Assert-Contains "docs/disaster-recovery-runbook.md" "RESTIC_REPOSITORY" "restic backup guidance"
Assert-Contains "docs/zh-CN/production-deployment-runbook.md" "DEPLOY_HOST=" "Chinese production deployment command"
Assert-Contains "docs/zh-CN/edge-proxy-runbook.md" "ORIGIN_UPSTREAM" "Chinese edge upstream variable"
Assert-Contains "docs/zh-CN/migration-runbook.md" "CONFIRM_FINAL_CUTOVER=yes" "Chinese migration confirmation"
Assert-Contains "docs/zh-CN/disaster-recovery-runbook.md" "RESTIC_REPOSITORY" "Chinese restic guidance"
Assert-Contains "package.json" '"e2e:web"' "Playwright browser e2e command"
Assert-Contains "playwright.config.ts" "KUMA_BASE_URL" "Kuma browser e2e base URL"
Assert-Contains "ops/live-e2e-billing-from-db-token.sh" "NEW_API_TEST_TOKEN_NAME" "live E2E token name"
Assert-Contains "ops/check-local-ports.sh" "KUMA_PORT" "local port checker"
Assert-Contains "AGENTS.md" "SPECKIT START" "Spec Kit context marker"
Assert-Contains ".specify/integration.json" '"integration": "codex"' "Codex Spec Kit integration"
Assert-Contains ".specify/integration.json" '"skills": true' "Codex skills integration"
Assert-Contains ".specify/init-options.json" '"speckit_version": "0.8.7"' "pinned Spec Kit version"
Assert-Contains "docs/templates/ai-dev/tasks.md" "Approved for implementation: no" "implementation approval default"
Assert-Contains "ops/ai-dev-check.sh" "Approved for implementation: yes" "implementation approval gate"
Assert-Contains "ops/production-gate.sh" "AI_DEV_FEATURE_DIR" "feature document production gate"
Assert-Contains "ops/production-gate.sh" "OPS_PROFILE_FILE" "ops profile production gate"
Assert-Contains "ops/production-gate.sh" "OPS_HEALTH_PROFILE_FILE" "channel health production gate"
Assert-Contains "ops/production-gate.sh" "tests/prod-deploy-migration.test.sh" "production deployment test"
Assert-Contains "ops/production-gate.sh" "tests/docs-i18n.test.sh" "documentation i18n test"
Assert-Contains "ops/production-gate.sh" "tests/git-branching-policy.test.sh" "git branching policy test"
Assert-Contains "ops/production-gate.sh" "tests/release-deploy.test.sh" "release deployment test"
Assert-Contains "ops/production-gate.sh" "docker-compose.prod.yml" "production compose gate"
Assert-Contains "ops/production-gate.sh" "docker-compose.edge.yml" "edge compose gate"
Assert-Contains "ops/deploy-prod.sh" "DEPLOY_HOST is not set" "deploy host gate"
Assert-Contains "ops/deploy-release.sh" "git worktree add --detach" "release worktree creation"
Assert-Contains "ops/deploy-release.sh" "docker compose -p" "fixed release compose project"
Assert-Contains "ops/deploy-release.sh" "ALLOW_NON_MAIN_PROD_DEPLOY" "release main production guard"
Assert-Contains "ops/offsite-backup.sh" "RESTIC_PASSWORD is not set" "restic password gate"
Assert-Contains "ops/migrate-prod.sh" "CONFIRM_FINAL_CUTOVER must be yes" "migration destructive gate"
Assert-Contains "ops/check-production-runtime.sh" "caddy port 443" "production runtime Caddy check"
Assert-Contains "ops/sync-cpa-upstream-assets.sh" "CLIProxyAPI/main/docker-compose.yml" "CPA upstream sync"
Assert-Contains "ops/production-gate.sh" "tests/spec-kit-init.test.sh" "Spec Kit production gate test"
Assert-Contains "ops/production-gate.sh" "tests/channel-health-advisor.test.sh" "channel health production gate test"
Assert-Contains "config/ops-profiles/glm-standard.example.json" "glm-5.1" "GLM standard ops profile model"
Assert-Contains "config/ops-profiles/glm-standard-health.example.json" "max_error_rate" "GLM standard health threshold"
Assert-Contains ".gitignore" "snapshots/" "configuration snapshots ignored"
Assert-Contains ".gitignore" "\.agents/\*\*" "agent private artifacts ignored"

Assert-NotContains ".env.example" "sk-[A-Za-z0-9]" "real-looking API keys"

if (-not $SkipDocker) {
    $docker = Get-Command docker -ErrorAction SilentlyContinue
    if ($docker) {
        Push-Location $root
        try {
            docker compose --env-file .env.example config | Out-Null
            docker compose --env-file .env.example -f docker-compose.yml -f docker-compose.prod.yml config | Out-Null
            docker compose --env-file .env.production.example -f docker-compose.edge.yml config | Out-Null
        }
        finally {
            Pop-Location
        }
    }
}

Write-Host "Repository verification passed."
